FROM alpine

# CREATE WORK DIRECTORY AND COPY SHELLCHAT FILES TO WORK DIR
WORKDIR /ShellChat

COPY . /ShellChat

# UPDATE
RUN apk update

# ADDING DEPENDENCIES
RUN apk add --no-cache bash
RUN apk add --no-cache g++
RUN apk add --no-cache make 
RUN apk add --no-cache ncurses-dev

# BUILD PROJECT
RUN make

# EXECUTE PROJECT (EXP)